---
- hosts: all
  sudo: false
  vars:
    php_packages: ["php5-xdebug", "php5-cli", "php5-curl", "php5-mysqlnd", "php5-intl", "php5-apcu", "php5-mongo", "php5-redis", "php5-mcrypt"]
  roles:
    - { role: jenkins, tags: jenkins }
    - { role: php5, tags: php5 }
