---
  - name: APT | Install dotdeb.org key
    apt_key: 
      id: 89DF5277
      url: http://www.dotdeb.org/dotdeb.gpg
      state: present

  - name: Add DotDeb wheezy-php55 repository
    apt_repository:
      repo: deb http://packages.dotdeb.org wheezy-php55 all
      state: present
      update_cache: yes

  - name: Install PHP packages
    apt: pkg={{ item }} state=installed
    with_items: php_packages

  - name: PHP5 | Set custom PHP settings
    template: src={{ php5_custom_template|default("custom.ini.j2") }} dest=/etc/php5/mods-available/custom.ini mode=0644
    notify:
      - restart php5-fpm

  - name: PHP5 | Set custom APCU settings
    template: src=apcu.ini.j2 dest=/etc/php5/mods-available/apcu.ini mode=0644
    when: "'php5-apcu' in php_packages"
    notify:
      - restart php5-fpm

  - name: PHP5 | Link FPM conf.d to custom PHP settings
    action: file src=/etc/php5/mods-available/custom.ini dest=/etc/php5/fpm/conf.d/99-custom.ini state=link
    when: "'php5-fpm' in php_packages"
    notify:
      - restart php5-fpm

  - name: PHP5 | Link CLI conf.d to custom PHP settings
    action: file src=/etc/php5/mods-available/custom.ini dest=/etc/php5/cli/conf.d/99-custom.ini state=link
    when: "'php5-cli' in php_packages"
